import {useEffect,useMemo,useState} from 'react'
import {auth,from,ownerEmail} from './supabase.js'
import {loadLibrary,buildIndex} from './data.js'
const statuses={planned:'Plan to watch',watching:'Watching',completed:'Completed',on_hold:'On hold',dropped:'Dropped'}
const date=v=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(v))
const palette=['#465c6c','#6b4d64','#4a685f','#76603f','#5a5473','#78534b']
function Cover({t}){return <div className="cover" style={{background:palette[t.display_title.length%palette.length]}}><small>{t.is_anime?'ANIME':t.media_type==='movie'?'FILM':'SERIES'}</small><strong>{t.display_title}</strong><small>{t.release_year||'MARQUEE'}</small></div>}
function Bar({done,total}){return <div className="bar" aria-label={`${done} of ${total} complete`}><span style={{width:`${total?done/total*100:0}%`}}/></div>}
function Login(){const[p,setP]=useState(''),[msg,setMsg]=useState('');return <div className="login"><div className="logo">✦</div><p className="kicker">YOUR SCREEN JOURNAL</p><h1>Marquee</h1><p>All your stories, in one private place.</p><form onSubmit={async e=>{e.preventDefault();const{error}=await auth.signInWithPassword({email:ownerEmail,password:p});if(error)setMsg(error.message)}}><label>GameDeck password<input type="password" autoComplete="current-password" value={p} onChange={e=>setP(e.target.value)} required/></label><button className="primary">Sign in</button></form><button className="link" onClick={async()=>{const{error}=await auth.signInWithOtp({email:ownerEmail,options:{emailRedirectTo:location.origin}});setMsg(error?.message||'Check your email. The preview URL must be allowed in Supabase Auth redirects.')}}>Email me a sign-in link</button>{msg&&<p role="alert">{msg}</p>}</div>}
function Evidence({history=[],undated}){return <section className="evidence"><h2>Watch record</h2>{undated&&<div className="evidenceRow"><b>✓ Historical completion</b><small>Date unverified · counts once toward progress</small></div>}{history.map(h=><div className="evidenceRow" key={h.id}><b>◷ {date(h.watched_at)}</b><small>Dated watch · {h.source==='manual'?'You':h.source==='trakt'?'Trakt':h.source}</small></div>)}{!history.length&&!undated&&<p className="muted">No completion recorded.</p>}</section>}
export default function App(){const[session,setSession]=useState(undefined),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('Library'),[filter,setFilter]=useState('All'),[query,setQuery]=useState(''),[titleId,setTitle]=useState(null),[seasonId,setSeason]=useState(null),[episodeId,setEpisode]=useState(null),[toast,setToast]=useState('')
useEffect(()=>{let live=true;auth.getSession().then(({data})=>{if(live)setSession(data.session?.user?.email?.toLowerCase()===ownerEmail?data.session:null)});const{data:listener}=auth.onAuthStateChange((_,s)=>{if(live)setSession(s?.user?.email?.toLowerCase()===ownerEmail?s:null)});return()=>{live=false;listener.subscription.unsubscribe()}},[])
async function refresh(){try{setData(await loadLibrary());setError('')}catch(e){setError(e.message)}}
useEffect(()=>{if(session)refresh();else setData(null)},[session?.user?.id])
const ix=useMemo(()=>data?buildIndex(data):null,[data]);const title=ix?.titles.find(t=>t.id===titleId),season=ix?.seasons.get(seasonId),episode=ix?.episodes.get(episodeId)
function close(){if(episodeId)setEpisode(null);else if(seasonId)setSeason(null);else setTitle(null)}
useEffect(()=>{function onKey(e){if(e.key==='Escape')close()}window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[episodeId,seasonId,titleId])
async function mutation(task,message){setBusy(true);setError('');try{await task();await refresh();setToast(message);setTimeout(()=>setToast(''),3500)}catch(e){setError(e.message)}finally{setBusy(false)}}
async function save(table,column,id,field,value){const old=data[table.replace('marquee_','')].find(x=>x[column]===id);const payload={user_id:session.user.id,[column]:id,[field]:value,source:'manual',manual_locked:true,updated_at:new Date().toISOString()};const{error}=old?await from(table).update(payload).eq('id',old.id):await from(table).insert(payload);if(error)throw error}
function checkIn(target,column){mutation(async()=>{const{error}=await from('marquee_watch_history').insert({user_id:session.user.id,[column]:target.id,source:'manual',watched_at:new Date().toISOString(),logical_event_key:`manual:${crypto.randomUUID()}`});if(error)throw error},'Watch recorded · progress counts this title once')}
function watchlist(){mutation(async()=>{const old=ix.watchlist.has(title.id);const{error}=old?await from('marquee_watchlist').delete().eq('title_id',title.id).eq('user_id',session.user.id):await from('marquee_watchlist').insert({user_id:session.user.id,title_id:title.id,source:'manual',manual_locked:true});if(error)throw error},ix.watchlist.has(title.id)?'Removed from watchlist':'Added to watchlist')}
const listed=ix?.titles.filter(t=>{if(tab==='Watchlist'&&!ix.watchlist.has(t.id))return false;if(tab==='Library'&&!ix.watchlist.has(t.id)&&!ix.statuses.has(t.id)&&!ix.byShow.get(t.id)?.some(s=>ix.seasonStatuses.has(s.id))&&!ix.progress(t).done)return false;if(filter==='Anime'&&!t.is_anime)return false;if(filter==='Series'&&(t.media_type!=='show'||t.is_anime))return false;if(filter==='Films'&&t.media_type!=='movie')return false;if(filter==='In progress'&&ix.statuses.get(t.id)?.status!=='watching'&&!ix.byShow.get(t.id)?.some(s=>ix.seasonStatuses.get(s.id)?.status==='watching'))return false;return t.display_title.toLowerCase().includes(query.toLowerCase().trim())}).sort((a,b)=>a.display_title.localeCompare(b.display_title))||[]
if(session===undefined)return <div className="loading">✦ Marquee</div>;if(!session)return <Login/>;if(!ix)return <div className="loading">{error?<><p>{error}</p><button onClick={refresh}>Try again</button></>:'Opening your library…'}</div>
return <div className="app"><header><b><span>✦</span> MARQUEE</b><button aria-label="Sign out" onClick={()=>auth.signOut()}>↗</button></header><main>
{!title&&<><div className="intro"><small className="kicker">YOUR PERSONAL SCREEN JOURNAL</small><h1>{tab}</h1><p>{tab==='Activity'?'Confirmed watch dates from Trakt and your check-ins.':tab==='Explore'?'Browse the existing catalog.':tab==='Watchlist'?'Stories saved for later.':'Pick up a story or revisit a favorite.'}</p></div>{tab!=='Activity'?<><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles" aria-label="Search titles"/></div><div className="chips">{['All','Anime','Series','Films','In progress'].map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><div className="section"><h2>{tab==='Explore'?'All titles':tab==='Watchlist'?'Saved for later':'Your collection'}</h2><small>{listed.length} titles</small></div><div className="list">{listed.map(t=>{const p=ix.progress(t);return <button className="row" key={t.id} onClick={()=>setTitle(t.id)}><Cover t={t}/><div className="rowText"><b>{t.display_title}</b><small>{t.is_anime?'Anime':t.media_type==='movie'?'Film':'Series'}{t.release_year?` · ${t.release_year}`:''}{ix.statuses.get(t.id)?` · ${statuses[ix.statuses.get(t.id).status]}`:''}</small><div className="progress"><Bar {...p}/><small>{t.media_type==='movie'?(p.done?'Watched':'Unwatched'):p.total?`${p.done} / ${p.total} episodes`:'Episodes pending'}</small></div></div><span className="arrow">›</span></button>})}{!listed.length&&<div className="empty">No titles match this view.</div>}</div></>:<><div className="callout">Historical anime completions count in season progress. Their dates are unverified, so they do not appear in this date ordered feed.</div><div className="section"><h2>Dated watches</h2></div><div className="list">{data.watch_history.filter(h=>h.source==='trakt'||h.source==='manual').sort((a,b)=>b.watched_at.localeCompare(a.watched_at)).slice(0,50).map(h=>{const ep=ix.episodes.get(h.episode_id),s=ix.seasons.get(ep?.season_id),t=ix.titles.find(t=>t.id===(h.movie_title_id||s?.show_title_id));return t&&<button className="activity" key={h.id} onClick={()=>{setTitle(t.id);setSeason(s?.id||null);setEpisode(ep?.id||null)}}><span>●</span><div><b>{t.display_title}</b><small>{ep?`Episode ${ep.episode_number??'special'}`:'Film'} · {h.source==='trakt'?'Trakt':'You'}</small></div><time>{date(h.watched_at)}</time></button>})}</div></>}</>}
{title&&<><button className="back" onClick={close}>‹ {episode?'Episode':season?'Season':tab}</button>{!season&&<><div className="hero"><Cover t={title}/><div><small className="kicker">{title.is_anime?'ANIME':title.media_type==='movie'?'FILM':'SERIES'} · {title.release_year||'—'}</small><h1>{title.display_title}</h1><Bar {...ix.progress(title)}/><small>{title.media_type==='movie'?(ix.progress(title).done?'Watched':'Not watched'):`${ix.progress(title).done} of ${ix.progress(title).total} episodes`}</small></div></div>{title.synopsis&&<p className="synopsis">{title.synopsis}</p>}<div className="actions"><button onClick={watchlist} disabled={busy}>{ix.watchlist.has(title.id)?'✓ In watchlist':'+ Watchlist'}</button>{title.media_type==='movie'&&<button onClick={()=>checkIn(title,'movie_title_id')} disabled={busy}>+ Log a watch</button>}</div><div className="controls"><label>Status<select value={ix.statuses.get(title.id)?.status||''} disabled={busy} onChange={e=>mutation(()=>save('marquee_statuses','title_id',title.id,'status',e.target.value),'Status saved')}><option value="" disabled>Choose status</option>{Object.entries(statuses).map(([key,value])=><option value={key} key={key}>{value}</option>)}</select></label><label>Rating · out of 10<select value={ix.ratings.get(title.id)?.score||''} disabled={busy} onChange={e=>mutation(()=>save('marquee_ratings','title_id',title.id,'score',Number(e.target.value)),'Rating saved')}><option value="" disabled>Choose rating</option>{Array.from({length:20},(_,i)=>(i+1)/2).map(n=><option key={n}>{n}</option>)}</select></label></div>{title.media_type==='movie'?<Evidence history={ix.history.get(title.id)} undated={ix.movieCoverage.get(title.id)?.has_undated_completion}/>:<><div className="section"><h2>Seasons</h2><small>{(ix.byShow.get(title.id)||[]).length}</small></div><div className="list">{(ix.byShow.get(title.id)||[]).map(s=>{const es=ix.bySeason.get(s.id)||[],done=es.filter(e=>ix.coverage.has(e.id)).length;return <button className="seasonRow" key={s.id} onClick={()=>setSeason(s.id)}><span className="number">{s.season_number===null?'SP':String(s.season_number).padStart(2,'0')}</span><div><b>{s.display_title||`Season ${s.season_number??'Specials'}`}</b><small>{es.length?`${done} of ${es.length} episodes`:statuses[ix.seasonStatuses.get(s.id)?.status]||'Episodes pending'}</small><Bar done={done} total={es.length}/></div><span className="arrow">›</span></button>})}</div></>}</>}
{season&&!episode&&<><small className="kicker">{title.display_title}</small><h1 className="detailTitle">{season.display_title||`Season ${season.season_number??'Specials'}`}</h1><p className="muted">{(ix.bySeason.get(season.id)||[]).filter(e=>ix.coverage.has(e.id)).length} of {(ix.bySeason.get(season.id)||[]).length} episodes complete</p><Bar done={(ix.bySeason.get(season.id)||[]).filter(e=>ix.coverage.has(e.id)).length} total={(ix.bySeason.get(season.id)||[]).length}/><div className="controls"><label>Season status<select value={ix.seasonStatuses.get(season.id)?.status||''} disabled={busy} onChange={e=>mutation(()=>save('marquee_statuses','season_id',season.id,'status',e.target.value),'Season status saved')}><option value="" disabled>Choose status</option>{Object.entries(statuses).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label>Season rating<select value={ix.seasonRatings.get(season.id)?.score||''} disabled={busy} onChange={e=>mutation(()=>save('marquee_ratings','season_id',season.id,'score',Number(e.target.value)),'Season rating saved')}><option value="" disabled>Choose rating</option>{Array.from({length:20},(_,i)=>(i+1)/2).map(n=><option key={n}>{n}</option>)}</select></label></div><div className="section"><h2>Episodes</h2></div><div className="list">{(ix.bySeason.get(season.id)||[]).map(e=><button className="episodeRow" key={e.id} onClick={()=>setEpisode(e.id)}><span className={'number '+(ix.coverage.has(e.id)?'done':'')}>{ix.coverage.has(e.id)?'✓':e.episode_number??'★'}</span><div><b>{e.display_title||`Episode ${e.episode_number??'Special'}`}</b><small>{ix.coverage.get(e.id)?.has_dated_watch?'Dated watch':ix.coverage.get(e.id)?.has_undated_completion?'Completed · date unverified':e.aired_at?`Aired ${date(e.aired_at)}`:'Not marked complete'}</small></div><span className="arrow">›</span></button>)}</div></>}
{episode&&<><small className="kicker">{title.display_title} · {season.display_title||`Season ${season.season_number??'Specials'}`}</small><h1 className="detailTitle">{episode.display_title||`Episode ${episode.episode_number??'Special'}`}</h1><p className="muted">{episode.episode_number?`Episode ${episode.episode_number} · `:''}{episode.runtime_minutes?`${episode.runtime_minutes} min · `:''}{episode.aired_at?`Aired ${date(episode.aired_at)}`:''}</p><Evidence history={ix.history.get(episode.id)} undated={ix.coverage.get(episode.id)?.has_undated_completion}/><button className="primary full" onClick={()=>checkIn(episode,'episode_id')} disabled={busy}>+ Check in this episode now</button><p className="muted">This records today as a new watch. Progress counts this canonical episode once across all sources.</p></>}</>}
{error&&<div className="alert" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}{toast&&<div className="toast" role="status">{toast}</div>}</main><nav>{[['Library','▤'],['Watchlist','◇'],['Activity','◷'],['Explore','⌕']].map(([name,icon])=><button className={tab===name?'active':''} key={name} onClick={()=>{setTab(name);setTitle(null);setSeason(null);setEpisode(null);setFilter('All');setQuery('');window.scrollTo(0,0)}}><span>{icon}</span>{name}</button>)}</nav></div>
}
